= Employee Manager
:author: Durang Vincent
:docdate: 2023-07-26
:asciidoctor-version: 1.1
:description: Gestion d'employés
:icons: font
:listing-caption: Listing
:toc-title: Les différents processus de conception
:toc: left
:toclevels: 4

== Présentation du projet

Employee Manager est une application de gestion d'employés qui suit le principe CRUD, c'est-à-dire qu'elle permet de créer, lire, modifier et supprimer des employés dans une base de données.

Les fonctionnalités de l'application incluent :

- Créer un employé : Cette fonctionnalité permet à l'utilisateur d'ajouter un nouvel employé à la base de données en saisissant les informations telles que le nom, le prénom, le poste, le numéro de téléphone, etc.

- Lire un employé : Grâce à cette option, l'utilisateur peut consulter la liste complète de tous les employés enregistrés dans la base de données. Cela permet d'avoir une vue d'ensemble de tous les membres du personnel.

- Modifier un employé : L'application permet à l'utilisateur de mettre à jour les informations d'un employé existant. Si un employé change de poste, de numéro de téléphone ou toute autre donnée, cette fonctionnalité permet de mettre à jour ces informations dans la base de données.

- Supprimer un employé : Si un employé quitte l'entreprise ou n'est plus nécessaire dans la base de données, cette fonctionnalité permet de le supprimer définitivement de la liste des employés enregistrés.

En plus de ces fonctionnalités, Employee Manager offre une option pratique pour ajouter un ou plusieurs employés à partir d'un fichier. Cela permet à l'utilisateur de charger facilement des informations d'employés à partir d'un document texte ou CSV, évitant ainsi la saisie manuelle pour une intégration plus rapide.

== Outils

- Environnement de développement intégré (IDE) : Intellij IDEA
- Langage de programmation : JAVA
- Base de données : MySQL
- Framework : Spring Boot

== Rapport

=== Installation et configuration des outils

Après avoir installé Intellij IDEA, j'utilise Spring Initializr (https://start.spring.io) pour générer l'application.

Options sélectionnées :

Projet : Maven
Langage : Java
Spring Boot : 3.1.2
Packaging : Jar
Java : SDK 17

Dépendances sélectionnées :

- Spring Boot DevTools
- Spring Web
- Spring Session
- Thymeleaf
- Bootstrap
- Spring Data JPA

Après avoir terminé la configuration et initialisé l'application, je lance celle-ci avec Intellij IDEA. Je vérifie que l'application se lance correctement et que les dépendances sont bien implémentées. Ensuite, je lance mon environnement local (ici, Laragon). Facultativement, je crée un contrôleur de test pour vérifier que le port et la session sont bien configurés.

=== Configuration de la base de données

Avant de configurer la base de données dans l'application, il faut la créer au préalable. Pour cela, j'utilise MySQL.

Pour me connecter à MySQL en ligne de commande :


[source,mysql]
----
mysql -u VOTRE_UTILISATEUR -p
----

Pour créer une base de données :

[source,mysql]
----
CREATE DATABASE nom_de_la_base_de_donnees;
----

Pour créer un utilisateur :

[source,mysql]
----
CREATE USER 'mon_utilisateur'@'localhost' IDENTIFIED BY 'mon_mot_de_passe';
----

Pour donner les privilèges à l'utilisateur créé :

[source,mysql]
----
GRANT ALL PRIVILEGES ON nom_de_la_base_de_donnees.* TO 'nom_utilisateur'@'hote';
----


Pour voir les bases de données ou les utilisateurs créés :



[source,mysql]
----
SHOW DATABASES;
----


[source,mysql]
----
SELECT User, Host FROM mysql.user;
----


Maintenant que la base de données est créée, il faut configurer le fichier application.properties (src/main/java/resources/application.properties) :


----
# Cette propriété contrôle la manière dont Hibernate gère le schéma de la base de données.
# "update" signifie qu'Hibernate va essayer de mettre à jour le schéma de la base de données en fonction des mappings d'entités.
# Si les tables existent déjà, il les modifiera pour correspondre aux nouveaux mappings d'entités.
# Si les tables n'existent pas, il les créera. Faites attention, car cela peut entraîner une perte de données.
spring.jpa.hibernate.ddl-auto=update

# Configuration du port du serveur.
server.port=8080

# Propriétés de configuration du DataSource pour se connecter à la base de données MySQL.
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/dataemployee
spring.datasource.username=springuser
spring.datasource.password=ThePassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cette propriété affiche les requêtes SQL dans les journaux de l'application (true/false).
# Décommentez la ligne suivante pour activer l'affichage des requêtes SQL.
# spring.jpa.show-sql=true

# Propriétés de configuration du serveur Tomcat pour gérer les téléchargements de gros fichiers.
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB

# Propriétés de configuration de l'upload de fichiers multipart avec Spring.
spring.servlet.multipart.enabled=true
spring.servlet.multipart.fileSizeThreshold=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.maxFileSize=100MB
spring.servlet.multipart.maxRequestSize=100MB
----

=== Configuration des modules

Je crée les packages controller, dto, entity, repository et service. Dans chaque package, je vais créer les modules correspondants.

* L'entité (à modifier) :

[source,java]
----
package com.example.employeemanager.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "EMPLOYEE")
public class Employee {
    @Id
    @GeneratedValue
    private Long id;

    @Column(name = "Nom")
    private String name;

    public Employee() {
    }

    public Employee(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
----

* Le controller

[source,java]
----
@Controller
public class EmployeeController {

  private EmployeeService employeeservice;

    public EmployeeController(EmployeeService employeeservice) {
        this.employeeservice = employeeservice;
    }

    @GetMapping("/home")
    public String getString() {
        return "main/home";

    }
----

* Le DTO

[source,java]
----

package com.example.employeemanager.dto;

public class EmployeeDTO {
    private String nom; // Correspond au champ "name" du formulaire

    public EmployeeDTO() {
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }
}
----

* Le repository (une interface contrairement aux autres modules qui sont des classes Java) :

[source,java]
----
public interface EmployeeRepository extends CrudRepository<Employee, String> {
}
----

* Le service

[source,java]
----
@Service
public class EmployeeService {
    private EmployeeRepository employeeRepository;

    public EmployeeService(EmployeeRepository employeeRepository) {
        this.employeeRepository = employeeRepository;
    }

    public void ajout( Employee employee){
        this.employeeRepository.save(employee);
    }

}
----

=== Rajout de l'option pour ajouter un employé

Après avoir créé les modules nécessaires, nous pouvons maintenant implémenter la fonctionnalité d'ajout d'un employé. Pour cela, nous allons ajouter deux nouvelles méthodes : une avec GetMapping pour afficher la page de formulaire et une avec PostMapping pour traiter l'ajout des données saisies.

Avant de procéder à cela, nous allons d'abord créer une méthode dans le contrôleur EmployeeController pour diriger vers la vue d'accueil :

[source,java]
----
@GetMapping("/home")
public String getString(Model model) {
return "main/home";
    }
----

Nous utiliserons Bootstrap pour styliser les pages et créerons deux fichiers : fragments pour l'en-tête et le pied de page, et main pour les pages principales. Dans fragments, nous ajouterons une barre de navigation qui sera utilisée sur toutes les pages. Ensuite, nous créerons home.html (qui n'est pas encore utile pour le moment) et ajouter.html.

Dans ajouter.html, nous allons créer un formulaire pour ajouter un nouvel employé :

[source,html]
----
<div class="container">
    <h2 class="mt-4 mb-4">Ajouter un Employee</h2>

    <form action="#" th:action="@{/ajouter}" method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="nom">Nom :</label>
            <input type="text" class="form-control" id="nom" name="nom" required>
        </div>

        <div class="form-group">
            <label for="prenom">Prénom :</label>
            <input type="text" class="form-control" id="prenom" name="prenom" required>
        </div>

        <div class="form-group">
            <label for="poste">Poste :</label>
            <input type="text" class="form-control" id="poste" name="poste" required>
        </div>

        <div class="form-group">
            <label for="num">Numéro de Telephone :</label>
            <input type="text" class="form-control" id="num" name="num" required>
        </div>

        <div class="form-group">
            <label for="email">Email :</label>
            <input type="text" class="form-control" id="email" name="email" required>
        </div>

        <div class="form-group">
            <label for="salaire">Salaire :</label>
            <input type="text" class="form-control" id="salaire" name="salaire" required>
        </div>

        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</div>
----

Nous avons également ajouté les autres valeurs (prénom, salaire, etc.) à l'entité Employee :
Faire attention lors de la génération d'id (il est important de choisir la bonne stratégie, dans notre ces strategy = GenerationType.IDENTITY)
Erreur : Bien choisir la strategy de generation d'id avant la création de la base de donnée, si vous la changer en cours de route il va avoir un conflit entre l'app et la base de données (dans certains cas on peut la changer manuellement.)

[source,java]
----
@Entity
@Table(name = "EMPLOYEE")
public class Employee {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "Nom")
    private String name;

    @Column(name = "Prenom")
    private String prenom;

    @Column(name = "Poste")
    private String poste;

    @Column(name = "Numéro")
    private String num;


    @Column(name = "Email")
    private String email;

    @Column(name = "Salaire")
    private String salaire;

----

(Nous avons également ajouté les getter et setter dans le DTO).

Ensuite, nous allons ajouter les deux méthodes mentionnées précédemment :

[source,java]
----
@GetMapping("/ajouter")
public String GetAjout(){
return "main/ajouter";
}
----

Le `GetMapping` redirigera l'utilisateur vers notre formulaire.


[source,java]
----
@PostMapping("/ajouter")
    public String ajouter(@ModelAttribute EmployeeDTO employeeDTO) {
        Employee employee = new Employee();
        employee.setName(employeeDTO.getNom());
        employee.setPrenom(employeeDTO.getPrenom());
        employee.setPoste(employeeDTO.getPoste());
        employee.setNum(employeeDTO.getNum());
        employee.setEmail(employeeDTO.getEmail());
        employee.setSalaire(employeeDTO.getSalaire());

        employeeservice.ajouter(employee);

        return "redirect:/home";

    }
----

Le `PostMapping` traitera les données du formulaire. N'oubliez pas d'inclure cette ligne (dans le form) dans `ajouter.html` :

[source,html]
----
<form action="#" th:action="@{/ajouter}" method="POST" enctype="multipart/form-data">
----

N'oubliez pas d'inclure enctype="multipart/form-data" dans notre cas et assurez-vous de ne pas vous tromper dans l'action.

Faite des tests pour vérifier le bon fonctionnement, s'il y a des erreurs regarder les anciennes étapes, et faire attention aux fautes de frappes.
Nous pouvons ajouter de nouveaux employés.

=== Rajout de l'option pour voir les employés.

Pour afficher les employés de la base de données sur la page d'accueil (`home`), nous devons effectuer quelques modifications. Nous ajouterons la liste des employés à l'attribut du modèle (`model`) en utilisant la méthode `findAll()` du repository `employeeRepository`. Ensuite, nous utiliserons cette liste dans le fichier HTML `home.html` en utilisant les fonctionnalités de Thymeleaf pour effectuer une boucle et afficher les informations de chaque employé.

Voici les modifications à apporter dans le contrôleur `EmployeeController` :


[source,java]
----
@GetMapping("/home")
    public String getHome(Model model) {
        model.addAttribute("employees", employeeRepository.findAll());
        return "main/home";

    }
----

Le `employeeRepository.findAll()` récupérera tous les employés et les stockera dans l'attribut `employees` du modèle. Maintenant, nous allons effectuer les modifications dans le fichier `home.html` . Nous utiliserons la variable `employees` du modèle pour itérer sur la liste et afficher les informations de chaque employé dans un tableau.

Voici le tableau dans home.html :

[source,html]
----
<table class="table">
    <thead>
    <tr class="table-dark">

        <th scope="col">Nom</th>
        <th scope="col">Prénom</th>
        <th scope="col">Poste</th>
        <th scope="col">Email</th>
        <th scope="col">Num</th>
        <th scope="col">Salaire</th>

    </tr>
    </thead>

    <tbody>
    <th:block th:each="employee : ${employees}">
        <tr class="table-bordered">
            <td th:text="${employee.name}">Nom</td>
            <td th:text="${employee.prenom}">Prenom</td>
            <td th:text="${employee.poste}">Poste</td>
            <td th:text="${employee.email}">Email</td>
            <td th:text="${employee.num}">Num</td>
            <td th:text="${employee.salaire}">Salaire</td>
        </tr>
    </th:block>

    </tbody>
    </table>
----

Nous utilisons `th:each="employee : ${employees}"` pour parcourir chaque employé dans la liste `employees`. Ensuite, nous affichons les informations de chaque employé dans les cellules du tableau en utilisant `th:text="${employee.name}"`, `th:text="${employee.prenom}"`, etc.

=== Rajout de l'option pour modifier les employés.

Pour permettre la modification d'un employé, nous devons d'abord récupérer l'ID de l'employé concerné. Pour cela, nous allons ajouter de nouvelles méthodes `GetMapping` et `PostMapping`.




Pour obtenir l'ID de l'employé, nous devons implémenter une méthode `getIdByEmployee` qui utilisera une fonction du repository pour retourner l'employé correspondant à l'ID fourni.

Voici la méthode ``getIdByEmployee`` dans le service ``EmployeeService`` :


[source,java]
----
 public Optional<Employee> GetIdByEmployee(Long id){
       return this.employeeRepository.findById(id.toString());
    }
----

Nous utilisons ``Optional`` pour gérer le cas où aucun employé n'est trouvé. Nous convertissons l'ID en chaîne de caractères car ``findById`` attend un ID de type ``String``.

Maintenant, nous pouvons implémenter les méthodes ``GetMapping`` et ``PostMapping``.

Le ``GetMapping`` aura besoin de l'ID de l'employé, que nous transmettrons via l'URL en utilisant ``@PathVariable``.

Voici le ``GetMapping`` :

[source,java]
----
 @GetMapping("/modifier/{id}")
    public String GetModifier(@PathVariable("id") Long id, Model model){
        Optional<Employee> employeeOptional = employeeservice.GetIdByEmployee(id);

        if (employeeOptional.isPresent()) {
            Employee employee = employeeOptional.get();
            model.addAttribute("employee",employee);
            return "main/modifier";
        } else {
            return "redirect:home";
        }

    }
----

Nous utilisons la méthode précédente ``getIdByEmployee(id)`` pour obtenir l'employé correspondant à l'ID passé via l'URL grâce à ``@PathVariable("id")``. L'employé est stocké dans ``employeeOptional``, et nous vérifions ensuite s'il est présent et non nul.

Pour le ``PostMapping``, le processus est similaire, mais nous utiliserons également l'ID de l'employé.

[source,java]
----
@PostMapping("/modifier/{id}")
    public String modifier(@PathVariable("id") Long id, @ModelAttribute EmployeeDTO employeeDTO) {
        Optional<Employee> employeeOptional = employeeservice.GetIdByEmployee(id);

        if (employeeOptional.isPresent()) {
            Employee employee = employeeOptional.get();
            employee.setName(employeeDTO.getNom());
            employee.setPrenom(employeeDTO.getPrenom());
            employee.setPoste(employeeDTO.getPoste());
            employee.setNum(employeeDTO.getNum());
            employee.setSalaire(employeeDTO.getSalaire());

            employeeservice.modifier(employee);

            return "redirect:/home";

        } else {
            return "redirect:/home";
        }
    }
----
Le processus est similaire, mais nous vérifions à nouveau si l'employé est présent, puis nous utilisons la méthode ``modifier`` du service pour mettre à jour les informations de l'employé dans la base de données.

[source,java]
----
public void modifier(Employee employee){
            employeeRepository.save(employee);
    }
----

Ensuite, nous devons ajouter un bouton de modification et créer le fichier ``modifier.html`` où nous placerons le formulaire de modification. Le bouton de modification transmettra l'ID à la méthode ``GetMapping``.


Voici le bouton de modification :

[source,html]
----
<a th:href="@{/modifier/{id}(id=${employee.id})}" class="btn btn-success">Modifier</a>
----

Dans ``modifier.html``, nous ajouterons le même formulaire que celui utilisé pour l'ajout, mais nous utiliserons ``th:action="@{/modifier/{id}(id=${employee.id})}"`` pour transmettre l'ID de l'employé et ``th:value="${employee.?}"`` pour chaque champ du formulaire (name, poste, etc.).

Voici le formulaire dans ``modifier.html`` :

[source,html]
----
<div class="container">
<h2 class="mt-4 mb-4">Modifier l'employees  </h2>

    <form action="#" th:action="@{/modifier/{id}(id=${employee.id})}" method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="nom">Nom :</label>
            <input type="text" class="form-control" id="nom" name="nom" th:value="${employee.name}" required>
        </div>

        <div class="form-group">
            <label for="prenom">Prénom :</label>
            <input type="text" class="form-control" id="prenom" name="prenom" th:value="${employee.prenom}" required>
        </div>

        <div class="form-group">
            <label for="poste">Poste :</label>
            <input type="text" class="form-control" id="poste" name="poste" th:value="${employee.poste}" required>
        </div>

        <div class="form-group">
            <label for="num">Numéro de Telephone :</label>
            <input type="text" class="form-control" id="num" name="num" th:value="${employee.num}" required>
        </div>

        <div class="form-group">
            <label for="email">Email :</label>
            <input type="text" class="form-control" id="email" name="email"th:value="${employee.email}" required>
        </div>

        <div class="form-group">
            <label for="salaire">Salaire :</label>
            <input type="text" class="form-control" id="salaire" name="salaire" th:value="${employee.name}" required>
        </div>

        <button type="submit" class="btn btn-primary">Modifier</button>
    </form>
</div>
----


=== Rajout d'option supprimer un employee

Pour supprimer un employee, nous aurons besoins de l'id de l'employee.
Ainsi, nous allons crée un nouveau GetMapping qui prend l'id en parametre, pour passer l'id @PathVariable est utiliser comme précedement pour modifier.
Nous appelerons une méthode de Service qui supprimera un employee de l'id fournit.

le GetMapping :

[source,java]
----
 @GetMapping("/supp/{id}")
    public String Getsupp(@PathVariable("id") Long id) {
        employeeservice.supp(id);
        return "redirect:/home";
    }
----

Pour la méthode supp de employeeservice, nous utiliserons une methode fournit par le repository grace CrudRepository.

Methode de supp dans employeeservice :

[source,java]
----
 public void supp(Long id){
        employeeRepository.deleteById(id.toString());
    }
----

Pour finir, nous implémenterons un bouton supprimer dans la liste employee de la meme maniere que pour modifier

Dans home.html :

[source,html]
----
 <a th:href="@{/supp/{id}(id=${employee.id})}" class="btn btn-danger">Supprimer</a></td>
----


=== Rajout d'employee via un fichier csv




