= Employee Manager
:author: Durang Vincent
:docdate: 2023-07-26
:asciidoctor-version: 1.1
:description: Gestion d'employés
:icons: font
:listing-caption: Listing
:toc-title: Les différents processus de conception
:toc: left
:toclevels: 4

== Présentation du projet

Employee Manager est une application de gestion d'employés qui suit le principe CRUD, c'est-à-dire qu'elle permet de créer, lire, modifier et supprimer des employés dans une base de données.

Les fonctionnalités de l'application incluent :

- Créer un employé : Cette fonctionnalité permet à l'utilisateur d'ajouter un nouvel employé à la base de données en saisissant les informations telles que le nom, le prénom, le poste, le numéro de téléphone, etc.

- Lire un employé : Grâce à cette option, l'utilisateur peut consulter la liste complète de tous les employés enregistrés dans la base de données. Cela permet d'avoir une vue d'ensemble de tous les membres du personnel.

- Modifier un employé : L'application permet à l'utilisateur de mettre à jour les informations d'un employé existant. Si un employé change de poste, de numéro de téléphone ou toute autre donnée, cette fonctionnalité permet de mettre à jour ces informations dans la base de données.

- Supprimer un employé : Si un employé quitte l'entreprise ou n'est plus nécessaire dans la base de données, cette fonctionnalité permet de le supprimer définitivement de la liste des employés enregistrés.

En plus de ces fonctionnalités, Employee Manager offre une option pratique pour ajouter un ou plusieurs employés à partir d'un fichier. Cela permet à l'utilisateur de charger facilement des informations d'employés à partir d'un document texte ou CSV, évitant ainsi la saisie manuelle pour une intégration plus rapide.

== Outils

- Environnement de développement intégré (IDE) : Intellij IDEA
- Langage de programmation : JAVA
- Base de données : MySQL
- Framework : Spring Boot

== Rapport

=== Installation et configuration des outils

Après avoir installé Intellij IDEA, j'utilise Spring Initializr (https://start.spring.io) pour générer l'application.

Options sélectionnées :

Projet : Maven
Langage : Java
Spring Boot : 3.1.2
Packaging : Jar
Java : SDK 17

Dépendances sélectionnées :

- Spring Boot DevTools
- Spring Web
- Spring Session
- Thymeleaf
- Bootstrap
- Spring Data JPA

Après avoir terminé la configuration et initialisé l'application, je lance celle-ci avec Intellij IDEA. Je vérifie que l'application se lance correctement et que les dépendances sont bien implémentées. Ensuite, je lance mon environnement local (ici, Laragon). Facultativement, je crée un contrôleur de test pour vérifier que le port et la session sont bien configurés.

1. Configuration de la base de données

Avant de configurer la base de données dans l'application, il faut la créer au préalable. Pour cela, j'utilise MySQL.

Pour me connecter à MySQL en ligne de commande :


[source,mysql]
----
mysql -u VOTRE_UTILISATEUR -p
----

Pour créer une base de données :

[source,mysql]
----
CREATE DATABASE nom_de_la_base_de_donnees;
----

Pour créer un utilisateur :

[source,mysql]
----
CREATE USER 'mon_utilisateur'@'localhost' IDENTIFIED BY 'mon_mot_de_passe';
----

Pour donner les privilèges à l'utilisateur créé :

[source,mysql]
----
GRANT ALL PRIVILEGES ON nom_de_la_base_de_donnees.* TO 'nom_utilisateur'@'hote';
----


Pour voir les bases de données ou les utilisateurs créés :



[source,mysql]
----
SHOW DATABASES;
----


[source,mysql]
----
SELECT User, Host FROM mysql.user;
----


Maintenant que la base de données est créée, il faut configurer le fichier application.properties (src/main/java/resources/application.properties) :


----
# Cette propriété contrôle la manière dont Hibernate gère le schéma de la base de données.
# "update" signifie qu'Hibernate va essayer de mettre à jour le schéma de la base de données en fonction des mappings d'entités.
# Si les tables existent déjà, il les modifiera pour correspondre aux nouveaux mappings d'entités.
# Si les tables n'existent pas, il les créera. Faites attention, car cela peut entraîner une perte de données.
spring.jpa.hibernate.ddl-auto=update

# Configuration du port du serveur.
server.port=8080

# Propriétés de configuration du DataSource pour se connecter à la base de données MySQL.
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/dataemployee
spring.datasource.username=springuser
spring.datasource.password=ThePassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cette propriété affiche les requêtes SQL dans les journaux de l'application (true/false).
# Décommentez la ligne suivante pour activer l'affichage des requêtes SQL.
# spring.jpa.show-sql=true

# Propriétés de configuration du serveur Tomcat pour gérer les téléchargements de gros fichiers.
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB

# Propriétés de configuration de l'upload de fichiers multipart avec Spring.
spring.servlet.multipart.enabled=true
spring.servlet.multipart.fileSizeThreshold=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.maxFileSize=100MB
spring.servlet.multipart.maxRequestSize=100MB
----

2. Configuration des modules

Je crée les packages controller, dto, entity, repository et service. Dans chaque package, je vais créer les modules correspondants.

* L'entité (à modifier) :

[source,java]
----
package com.example.employeemanager.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "EMPLOYEE")
public class Employee {
    @Id
    @GeneratedValue
    private Long id;

    @Column(name = "Nom")
    private String name;

    public Employee() {
    }

    public Employee(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
----

* Le controller

[source,java]
----
@Controller
public class EmployeeController {

  private EmployeeService employeeservice;

    public EmployeeController(EmployeeService employeeservice) {
        this.employeeservice = employeeservice;
    }

    @GetMapping("/home")
    public String getString() {
        return "main/home";

    }
----

* Le DTO

[source,java]
----

package com.example.employeemanager.dto;

public class EmployeeDTO {
    private String nom; // Correspond au champ "name" du formulaire

    public EmployeeDTO() {
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }
}
----

* Le repository (une interface contrairement aux autres modules qui sont des classes Java) :

[source,java]
----
public interface EmployeeRepository extends CrudRepository<Employee, String> {
}
----

* Le service

[source,java]
----
@Service
public class EmployeeService {
    private EmployeeRepository employeeRepository;

    public EmployeeService(EmployeeRepository employeeRepository) {
        this.employeeRepository = employeeRepository;
    }

    public void ajout( Employee employee){
        this.employeeRepository.save(employee);
    }

}
----

3- Rajout de l'option pour ajouter un employé

Après avoir créé les modules nécessaires, nous pouvons maintenant implémenter la fonctionnalité d'ajout d'un employé. Pour cela, nous allons ajouter deux nouvelles méthodes : une avec GetMapping pour afficher la page de formulaire et une avec PostMapping pour traiter l'ajout des données saisies.


Avant de procéder à cela, nous allons d'abord créer une méthode dans le contrôleur EmployeeController pour diriger vers la vue d'accueil :


[source,java]
----
@GetMapping("/home")
public String getString(Model model) {
return "main/home";
    }
----

PNous utiliserons Bootstrap pour styliser les pages et créerons deux fichiers : fragments pour l'en-tête et le pied de page, et main pour les pages principales. Dans fragments, nous ajouterons une barre de navigation qui sera utilisée sur toutes les pages. Ensuite, nous créerons home.html (qui n'est pas encore utile pour le moment) et ajouter.html.

Dans ajouter.html, nous allons créer un formulaire pour ajouter un nouvel employé :

[source,html]
----
<div class="container">
    <h2 class="mt-4 mb-4">Ajouter un Employee</h2>

    <form action="#" th:action="@{/ajouter}" method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="nom">Nom :</label>
            <input type="text" class="form-control" id="nom" name="nom" required>
        </div>

        <div class="form-group">
            <label for="prenom">Prénom :</label>
            <input type="text" class="form-control" id="prenom" name="prenom" required>
        </div>

        <div class="form-group">
            <label for="poste">Poste :</label>
            <input type="text" class="form-control" id="poste" name="poste" required>
        </div>

        <div class="form-group">
            <label for="num">Numéro de Telephone :</label>
            <input type="text" class="form-control" id="num" name="num" required>
        </div>

        <div class="form-group">
            <label for="email">Email :</label>
            <input type="text" class="form-control" id="email" name="email" required>
        </div>

        <div class="form-group">
            <label for="salaire">Salaire :</label>
            <input type="text" class="form-control" id="salaire" name="salaire" required>
        </div>

        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</div>
----

Nous avons également ajouté les autres valeurs (prénom, salaire, etc.) à l'entité Employee :

[source,java]
----
@Entity
@Table(name = "EMPLOYEE")
public class Employee {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "Nom")
    private String name;

    @Column(name = "Prenom")
    private String prenom;

    @Column(name = "Poste")
    private String poste;

    @Column(name = "Numéro")
    private String num;


    @Column(name = "Email")
    private String email;

    @Column(name = "Salaire")
    private String salaire;

----

(Nous avons également ajouté les getter et setter dans le DTO).

Ensuite, nous allons ajouter les deux méthodes mentionnées précédemment :

[source,java]
----
@GetMapping("/ajouter")
public String GetAjout(){
return "main/ajouter";
}
----

Le `GetMapping` redirigera l'utilisateur vers notre formulaire.


[source,java]
----
@PostMapping("/ajouter")
    public String ajouter(@ModelAttribute EmployeeDTO employeeDTO) {
        Employee employee = new Employee();
        employee.setName(employeeDTO.getNom());
        employee.setPrenom(employeeDTO.getPrenom());
        employee.setPoste(employeeDTO.getPoste());
        employee.setNum(employeeDTO.getNum());
        employee.setEmail(employeeDTO.getEmail());
        employee.setSalaire(employeeDTO.getSalaire());

        employeeservice.ajouter(employee);

        return "redirect:/home";

    }
----

Le `PostMapping` traitera les données du formulaire. N'oubliez pas d'inclure cette ligne dans `ajouter.html` :

[source,java]
----
<form action="#" th:action="@{/ajouter}" method="POST" enctype="multipart/form-data">
----

N'oubliez pas d'inclure enctype="multipart/form-data" dans notre cas et assurez-vous de ne pas vous tromper dans l'action.
